version: "3"

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink # pin the image version to Lavalink v4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
      - LAVALINK_SERVER_PASSWORD=youshallnotpass # set password for lavalink
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lavalink
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    ports:
      - 2333:2333 # you only need this if you want to make your lavalink accessible from outside of containers

  mongodb:
    container_name: mongodb
    ports:
      - 27017:27017
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: byteblaze
      MONGO_INITDB_ROOT_PASSWORD: cylane
    restart: on-failure
    networks:
      - mongodb-net
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb

  byteblaze:
    build: .
    image: byteblaze:latest
    container_name: byteblaze
    restart: unless-stopped
    networks:
      - lavalink
      - mongodb-net
    depends_on:
      - lavalink
      - mongodb
    environment:
      - DOCKER_COMPOSE_MODE=true
      # Database
      - MONGO_URI=mongodb://byteblaze:cylane@mongodb:27017/streamhatchet?directConnection=true&authSource=admin&replicaSet=replicaset&retryWrites=true
      # Lavalink
      - NODE_URL=lavalink:2333
      - NODE_AUTH=youshallnotpass

networks:
  mongodb-net:
  lavalink: # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink

volumes:
  mongodb_data:
