module.exports = {
      color: "00ffbe",
            timeouttime: "10m", // you can change time out time from here :)
            tm: "NONE", // 💀DONT TUCHE THIS PART DANGER 💀
            reason: "NONE",
    prefix: "a!",
  originalprefix: "a!",
    lvl: "0",
xp: "0",
reqxp: "300",
    lastblacklist: "Nobody",
rblacklist: "",
  vcCount: "",  
blacklist: "false",
lastunblacklist: "No one",
    warn: 0,
  cases: "{}",
    ServerId: "Null",
    RankLimit: "39",
    Cookie: "Null",
    placeId: "Null",
    auth: "Null",
    RankPerms: "Null",
    AdminRole: "Null",
    banauthor: "",
    banmessage: "",
    test: "",
    shoutcid: "Null",
    logchannel: "Null",
    ShoutId: "Null",
    blacklist: "false",
    blacklistreason: "No Reason Given.",
    salt: "10",
    tick_e: "false",
    tick_r: "",
    tick: "false",
    tick_c: "0",
    transcript_channel: "$channelID",
    tick_describe: "Hey, this is your ticket. Support will arrive shortly.",
    panel_titlen: "Open a ticket",
    ticket_title: "Ticket",
    panel_desc: "Click the button to open a ticket!",
    button_name: "Open ticket",
    ch_name: "tick",
    auto_tran: "false"

}
